GET http://localhost:3000/

###

POST  http://localhost:3000/admin/signup
Content-Type: application/json

{
    "name":"Veli",
    "surname":"Can",
    "email":"veli@gmail.com",
    "password":"123",
    "imageUrl":"https://mui.com/static/images/avatar/2.jpg"
}

###

POST  http://localhost:3000/admin/login
Content-Type: application/json

{
  
    "email":"mehmet.ztrk2134@gmail.com",
    "password":"123"
}


###

GET http://localhost:3000/message/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTWVobWV0Iiwic3VybmFtZSI6IsOWenTDvHJrIiwiZW1haWwiOiJtZWhtZXQuenRyazIxMzRAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkNEZLU0I1RFVFcUhtUWZLY3ZtVXRnT0FRRzE4TGRPTFFGam54MkdBNlgyNlVnd1p3VkpmcGkiLCJpbWFnZVVybCI6Imh0dHBzOi8vcHBzLndoYXRzYXBwLm5ldC92L3Q2MS4yNDY5NC0yNC8yOTQ5MDAyNjRfMTc2NTI3NTk3Mzg0NzEzMV82NDkzOTU1MDk1NDg4MzA0MDY2X24uanBnP3N0cD1kc3QtanBnX3M5Nng5NiZjY2I9MTEtNCZvaD0wMV9BVnhJYkFUS1FERDZrUE1lRi05bG9rQnowSXBRWlU0QTBBaXVDQTJKcmFxUjVRJm9lPTYzMTY3M0JEIiwiY3JlYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIiwidXBkYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIn0sImlhdCI6MTY2MTUzMjQ2MywiZXhwIjoxNjYxNTM2MDYzfQ.L_kslqbFJxfjsWwmvcXajTZnrvCPreFEp0XJfPIX--o   



###


POST  http://localhost:3000/message/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTWVobWV0Iiwic3VybmFtZSI6IsOWenTDvHJrIiwiZW1haWwiOiJtZWhtZXQuenRyazIxMzRAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkNEZLU0I1RFVFcUhtUWZLY3ZtVXRnT0FRRzE4TGRPTFFGam54MkdBNlgyNlVnd1p3VkpmcGkiLCJpbWFnZVVybCI6Imh0dHBzOi8vcHBzLndoYXRzYXBwLm5ldC92L3Q2MS4yNDY5NC0yNC8yOTQ5MDAyNjRfMTc2NTI3NTk3Mzg0NzEzMV82NDkzOTU1MDk1NDg4MzA0MDY2X24uanBnP3N0cD1kc3QtanBnX3M5Nng5NiZjY2I9MTEtNCZvaD0wMV9BVnhJYkFUS1FERDZrUE1lRi05bG9rQnowSXBRWlU0QTBBaXVDQTJKcmFxUjVRJm9lPTYzMTY3M0JEIiwiY3JlYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIiwidXBkYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIn0sImlhdCI6MTY2MTQyNDI5MCwiZXhwIjoxNjYxNDI3ODkwfQ.PuPUxqqqGnRWG7Mke2jc9_d-dB-GeETVZmpEBRNrCkE   

{
  
    "content":"naber veli",
    "reciverId":5
}

###

POST  http://localhost:3000/message/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiQWxpIiwic3VybmFtZSI6IkNhbiIsImVtYWlsIjoiYWxpQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEyJEpEaXVzSjRPaGhhRGRnak1GNDl6Uy5vVlYvUGhUMHZVckNYSVk1LnpiY29lTHVJSjFpS1BxIiwiaW1hZ2VVcmwiOiJodHRwczovL211aS5jb20vc3RhdGljL2ltYWdlcy9hdmF0YXIvMi5qcGciLCJjcmVhdGVkQXQiOiIyMDIyLTA4LTI0VDE0OjA2OjMxLjU4MloiLCJ1cGRhdGVkQXQiOiIyMDIyLTA4LTI0VDE0OjA2OjMxLjU4MloifSwiaWF0IjoxNjYxMzY5NjgxLCJleHAiOjE2NjEzNzMyODF9.96mu_kEA3MI4Fxstqn_nKEREqsnJbjZv-Clprbcv0lQ   

{
  
    "content":"Aldus PageMaker including versions of Lorem Ipsum.",
    "reciverId":1
}

###

POST http://localhost:3000/message/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTWVobWV0Iiwic3VybmFtZSI6IsOWenTDvHJrIiwiZW1haWwiOiJtZWhtZXQuenRyazIxMzRAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkNEZLU0I1RFVFcUhtUWZLY3ZtVXRnT0FRRzE4TGRPTFFGam54MkdBNlgyNlVnd1p3VkpmcGkiLCJpbWFnZVVybCI6Imh0dHBzOi8vcHBzLndoYXRzYXBwLm5ldC92L3Q2MS4yNDY5NC0yNC8yOTQ5MDAyNjRfMTc2NTI3NTk3Mzg0NzEzMV82NDkzOTU1MDk1NDg4MzA0MDY2X24uanBnP3N0cD1kc3QtanBnX3M5Nng5NiZjY2I9MTEtNCZvaD0wMV9BVnhJYkFUS1FERDZrUE1lRi05bG9rQnowSXBRWlU0QTBBaXVDQTJKcmFxUjVRJm9lPTYzMTY3M0JEIiwiY3JlYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIiwidXBkYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIn0sImlhdCI6MTY2MTM2MzQwMCwiZXhwIjoxNjYxMzY3MDAwfQ.z_4FNjT2KAEsB2baLNJM1sxt2QTol7boK8SO-OG481g

{
    "userId":2
}

###

POST  http://localhost:3000/admin/getUser
Content-Type: application/json

{
  
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTWVobWV0Iiwic3VybmFtZSI6IsOWenTDvHJrIiwiZW1haWwiOiJtZWhtZXQuenRyazIxMzRAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkNEZLU0I1RFVFcUhtUWZLY3ZtVXRnT0FRRzE4TGRPTFFGam54MkdBNlgyNlVnd1p3VkpmcGkiLCJpbWFnZVVybCI6Imh0dHBzOi8vcHBzLndoYXRzYXBwLm5ldC92L3Q2MS4yNDY5NC0yNC8yOTQ5MDAyNjRfMTc2NTI3NTk3Mzg0NzEzMV82NDkzOTU1MDk1NDg4MzA0MDY2X24uanBnP3N0cD1kc3QtanBnX3M5Nng5NiZjY2I9MTEtNCZvaD0wMV9BVnhJYkFUS1FERDZrUE1lRi05bG9rQnowSXBRWlU0QTBBaXVDQTJKcmFxUjVRJm9lPTYzMTY3M0JEIiwiY3JlYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIiwidXBkYXRlZEF0IjoiMjAyMi0wOC0yNFQxNDowNjoxOC42NzNaIn0sImlhdCI6MTY2MTUyMTIyNywiZXhwIjoxNjYxNTI0ODI3fQ.3wxbEFdz6KUFyHque8cv-jKXfjjE2k6rKDmksu01Oh0"
}